org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options=-Xmx1g
android.useAndroidX=true
android.enableJetifier=true

# Evita el error del compilador incremental de Kotlin con rutas en discos distintos
kotlin.incremental=false

# (opcional) más estabilidad del daemon
kotlin.compiler.execution.strategy=in-process
org.gradle.configuration-cache=false
org.gradle.caching=true
