// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get alreadyAnAccountLogin => 'Already have an account? Sign in';

  @override
  String get about => 'About';

  @override
  String get aboutText =>
      'This application is proposed to you by Thomas Simmer.';

  @override
  String get cancel => 'Cancel';

  @override
  String get changePassword => 'Change Password';

  @override
  String get challenges => 'Challenges';

  @override
  String get confirmDeletion => 'Confirm Deletion';

  @override
  String get confirmDeletionQuestion =>
      'Are you sure you want to delete the session on this device?';

  @override
  String get comeBack => 'Come Back';

  @override
  String get currentPassword => 'Current password';

  @override
  String get dark => 'Dark';

  @override
  String get defaultError => 'An error occurred. Please try again.';

  @override
  String get delete => 'Delete';

  @override
  String get devices => 'My devices';

  @override
  String deviceInfo(String isMobile, String os, String browser, String model) {
    String _temp0 = intl.Intl.selectLogic(
      isMobile,
      {
        'true': 'Mobile device',
        'false': 'Computer',
        'other': 'Unknown',
      },
    );
    String _temp1 = intl.Intl.selectLogic(
      os,
      {
        'null': '. ',
        'other': ' running on $os. ',
      },
    );
    String _temp2 = intl.Intl.selectLogic(
      browser,
      {
        'null': 'App',
        'other': 'Browser: $browser',
      },
    );
    String _temp3 = intl.Intl.selectLogic(
      model,
      {
        'null': '',
        'other': 'Model: $model.',
      },
    );
    return '$_temp0$_temp1$_temp2. $_temp3';
  }

  @override
  String get deviceDeleteSuccessful =>
      'You successfully stopped the session on this device';

  @override
  String get disableTwoFA => 'Disable';

  @override
  String get enable => 'Enable';

  @override
  String get enterOneTimePassword =>
      'Enter the 6-digit code generated by your app to confirm your authentication.';

  @override
  String get enterPassword => 'Enter your password.';

  @override
  String get enterRecoveryCode => 'Enter one of your recovery codes.';

  @override
  String get enterUsername => 'Enter your username.';

  @override
  String get enterValidationCode =>
      'Enter the code from your authentication app.';

  @override
  String get failedToLoadProfile => 'Failed to load profile';

  @override
  String get forbiddenError => 'You are not authorized to perform this action.';

  @override
  String get generateNewQrCode => 'Generate a new QR code';

  @override
  String get goToTwoFASetup => 'Set up two-factor authentication';

  @override
  String get habits => 'Employees';

  @override
  String hello(String userName) {
    return 'Hello $userName';
  }

  @override
  String get home => 'Home';

  @override
  String get internalServerError =>
      'An internal server error occurred. Please try again.';

  @override
  String get invalidOneTimePasswordError =>
      'Invalid one-time password. Please try again.';

  @override
  String get invalidRequestError =>
      'The request you made was not accepted by the server.';

  @override
  String get invalidResponseError =>
      'The response from the server could not be processed.';

  @override
  String get invalidUsernameOrCodeOrRecoveryCodeError =>
      'Invalid username, one-time password, or recovery code. Please try again.';

  @override
  String get invalidUsernameOrPasswordError =>
      'Invalid username or password. Please try again.';

  @override
  String get invalidUsernameOrPasswordOrRecoveryCodeError =>
      'Invalid username, password, or recovery code. Please try again.';

  @override
  String get invalidUsernameOrRecoveryCodeError =>
      'Invalid username or recovery code. Please try again.';

  @override
  String get keepRecoveryCodesSafe =>
      'Please keep these recovery codes safe.\nThey are necessary if you lose your password or access to your 2FA application.';

  @override
  String get language => 'Language';

  @override
  String get lastActivityDate => 'Last activity date:';

  @override
  String get light => 'Light';

  @override
  String get logIn => 'Log In';

  @override
  String get loginSuccessful => 'You successfully logged in.';

  @override
  String get logout => 'Log out';

  @override
  String get logoutSuccessful => 'You successfully logged out.';

  @override
  String get messages => 'Messages';

  @override
  String get newPassword => 'New password';

  @override
  String get next => 'Next';

  @override
  String get noAccountCreateOne => 'No account? Create one here.';

  @override
  String get noContent => 'No content to display';

  @override
  String get noDevices => 'No device to display';

  @override
  String get noDeviceInfo => 'No device information to display';

  @override
  String get noRecoveryCodeAvailable => 'No recovery codes available.';

  @override
  String get password => 'Password';

  @override
  String get passwordForgotten => 'Forgot your password?';

  @override
  String get passwordMustBeChangedError =>
      'You need to change your password to log in.';

  @override
  String get passwordNotComplexEnough =>
      'Your password must contain at least a letter, a digit, and a special character.';

  @override
  String get passwordNotExpiredError =>
      'Your password is not expired, so it cannot be changed this way.';

  @override
  String get passwordTooShortError =>
      'Your password must be at least 8 characters long.';

  @override
  String get passwordUpdateSuccessful =>
      'Your password was successfully updated.';

  @override
  String get pleaseLoginOrSignUp => 'Please log in or sign up to continue.';

  @override
  String get profile => 'Profile';

  @override
  String get profileSettings => 'Profile Settings';

  @override
  String get profileUpdateSuccessful => 'Profile information saved.';

  @override
  String get qrCodeSecretKeyCopied => 'QR code secret key copied to clipboard.';

  @override
  String get recoverAccount => 'Recover Account';

  @override
  String get recoveryCode => 'Recovery code';

  @override
  String get recoveryCodesCopied => 'Recovery codes copied to clipboard.';

  @override
  String get refreshTokenExpiredError =>
      'Your session has expired. Please log in again.';

  @override
  String get regenerateQrCode => 'Regenerate QR code';

  @override
  String get save => 'Save';

  @override
  String get selectLanguage => 'Select Language';

  @override
  String get selectTheme => 'Select Theme';

  @override
  String get setNewPassword => 'Enter your new password.';

  @override
  String get signUp => 'Sign Up';

  @override
  String get theme => 'Theme';

  @override
  String get twoFA => 'Two-Factor Authentication';

  @override
  String get twoFAInvitation =>
      'Security and privacy are our top priorities.\nPlease set up two-factor authentication to protect your account from brute-force attacks.';

  @override
  String get twoFAIsWellSetup =>
      'Two-Factor Authentication is successfully set up for your account.';

  @override
  String get twoFAScanQrCode =>
      'Scan this QR code with your authentication app.';

  @override
  String twoFASecretKey(String secretKey) {
    return 'Your secret key is: $secretKey';
  }

  @override
  String get twoFASetup =>
      'Enable two-factor authentication to secure your account.';

  @override
  String get twoFactorAuthenticationNotEnabledError =>
      'Two-factor authentication is not enabled for your account.';

  @override
  String get unableToLoadRecoveryCodes => 'Unable to load recovery codes.';

  @override
  String get unauthorizedError =>
      'You are not authorized to perform this action.';

  @override
  String get unknown => 'Unknown';

  @override
  String get unknownError => 'An unexpected error occurred. Please try again.';

  @override
  String get updatePassword => 'Enter your current and new password.';

  @override
  String get userAlreadyExistingError =>
      'A user with this username already exists. Please choose another.';

  @override
  String get userNotFoundError => 'User not found.';

  @override
  String get username => 'Username';

  @override
  String get usernameNotRespectingRulesError =>
      'Your username must follow these rules:\n - Start and end with a letter or digit\n - Allowed special characters are . _ -\n - No consecutive special characters';

  @override
  String get usernameWrongSizeError =>
      'Username length must be between 3 and 20 characters.';

  @override
  String get validationCode => 'Validation code';

  @override
  String get validationCodeCorrect => 'Your validation code is correct!';

  @override
  String get verify => 'Verify';

  @override
  String get welcome => 'Welcome on the Flutter Actix App.';

  @override
  String get previous => 'Previous';
}
